### ISSUE TITLE
Refresh and loadmore

### ISSUE THREAD

**Issue by AttemptD** [wxxsw/Refresh#2]
@wxxsw When I refresh, the method of loading more will also run at the same time. When I enter the page for the first time, I have to refresh once to perform loading more, otherwise my loading more can only be performed once. nomore is set to false

**Comment by wxxsw** [comment]
Yes, this is currently a bug, but due to the limitation of List, I can't solve it for now, but it can be avoided like this:
```swift
if items.count > 0 {
    RefreshFooter...
}

**Comment by AttemptD** [comment]
Thanks @wxxsw
