### ISSUE TITLE
Swift Packages 安装出错

### ISSUE THREAD

**Issue by boaaa** [wxxsw/Refresh#5]
选择版本安装时是空的！！

**Comment by wxxsw** [comment]
我这里没看到错误，我在这个项目里也是通过 SPM 进行安装 Refresh 的，你可以看一下 https://github.com/wxxsw/SwiftUI-WeChat

**Comment by SpectatorNan** [comment]
> 我这里没看到错误，我在这个项目里也是通过 SPM 进行安装 Refresh 的，你可以看一下 https://github.com/wxxsw/SwiftUI-WeChat

你需要release一个tag出来  SPM 才能搜索到

**Comment by wxxsw** [comment]
Release 0.1.
